const express = require("express")
const mongoose = require("mongoose")
const cors = require("cors")
require("dotenv").config()
const Joi = require("joi")
const joiObjectId = require("joi-objectid")
Joi.ObjectId = joiObjectId(Joi)
const clinicDepartments = require("./router/ClinicDepartments")
const users = require("./router/users")
const bloods = require("./router/bloods")
const analyzings = require("./router/analyzings")
const porgraams = require("./router/porgrams")
const appointments = require("./router/appointments")
const medicineRecords = require("./router/medicineRecords")
const rays = require("./router/rays")
const services = require("./router/services")
const vaccines = require("./router/vaccines")
const madacafiles = require("./router/madacalFile")
mongoose
  .connect(`mongodb://localhost:27017/ClincDB`)
  .then(() => {
    console.log("Connected to MongoDB")
  })
  .catch(error => {
    console.log("Error connecting to MongoDB ", error)
  })
const app = express()
app.use(express.json())
app.use(cors())
app.use("/api/clinicDepartments", clinicDepartments)
app.use("/api/auth", users)
app.use("/api/bloods", bloods)
app.use("/api/analyzings", analyzings)
app.use("/api/porgrams", porgraams)
app.use("/api/madacalfiles", madacafiles)
app.use("/api/appointments", appointments)
app.use("/api/medicineRecords", medicineRecords)
app.use("/api/services", services)
app.use("/api/rays", rays)
app.use("/api/vaccines", vaccines)
app.listen(5000, () => {
  console.log("server is listening on port:" + 5000)
})
